apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: ecomsite
spec:
  type: ClusterIP       # internal only
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 3000
