apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: ecomsite
spec:
  type: NodePort               # <-- changed from ClusterIP
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080         # <-- expose this port externally
